// Rule tables — the Python engine's tables (lazaret.scanner.core RULES /
// TEXT_RULES) with their pattern text copied VERBATIM and compiled with
// Python `re` semantics by pyRe() (Unicode \w/\b/\s, `.` ≠ "\n", Unicode
// case folding). Generated from the live Python tables, then extended with
// the linear-time matchers below. Where a Python pattern can backtrack
// super-linearly on adversarial input, the rule carries a `find(line)`
// function with the SAME match semantics in linear time; `re` stays the
// reference pattern.
// TODO(shared rule table): both engines could read one checked-in
// rules.json instead of carrying two copies (see the JS agent's report).

import { pyRe } from "../lib/pycompat.js";
import { findSecretToken } from "../lib/redact.js";
import { sqlDynamicFind, grantPublicFind, yamlLoadFind, chmodFind, emptyCatchScan, exceptPassScan } from "./linear.js";

export const SEV_ORDER = {BLOCKER:0, CRITICAL:1, MAJOR:2, MINOR:3, INFO:4};
export const TYPES = {VULN:"Vulnerability", HOTSPOT:"Security Hotspot", BUG:"Bug", SMELL:"Code Smell"};

// Line-based rules: {id,name,type,sev,langs,re,skip?,need?,find?,msg,why,fix,ref}
export const RULES = [
{
id:"S-EVAL-PY", name:"Dynamic code execution", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("(?<![\\w.])(eval|exec)\\s*\\(", ""),
 msg:"Use of eval/exec enables arbitrary code execution.",
 why:"If any part of the evaluated string derives from user input, an attacker can run arbitrary code in your process.",
 fix:"Replace with safe parsing (ast.literal_eval) or an explicit dispatch table.",
 ref:"CWE-95 · OWASP A03: Injection",
},
{
id:"S-EVAL-JS", name:"Dynamic code execution", type:"VULN", sev:"CRITICAL", langs:["js"],
 re:pyRe("(?<![\\w.])eval\\s*\\(", ""),
 msg:"Use of eval enables arbitrary code execution.",
 why:"If any part of the evaluated string derives from user input, an attacker can run arbitrary code.",
 fix:"Replace with JSON.parse or an explicit dispatch table.",
 ref:"CWE-95 · OWASP A03: Injection",
},
{
id:"S-NEWFUNC", name:"Function constructor", type:"VULN", sev:"CRITICAL", langs:["js"],
 re:pyRe("new\\s+Function\\s*\\(", ""),
 msg:"new Function() compiles strings into code, equivalent to eval.",
 why:"String-built functions can execute attacker-controlled input.",
 fix:"Define functions statically or use a whitelisted dispatch map.",
 ref:"CWE-95 · OWASP A03",
},
{
id:"S-SQL-PY", name:"SQL built from strings", type:"VULN", sev:"BLOCKER", langs:["py"],
 re:pyRe("\\.(execute|executemany)\\s*\\(\\s*(f[\\\"']|[\\\"'][^\\\"']*[\\\"']\\s*(%|\\+|\\.format))", ""),
 msg:"SQL query built with string formatting/concatenation.",
 why:"Interpolating values into SQL enables SQL injection — the classic path to full database compromise.",
 fix:"Use parameterized queries: cursor.execute(\"SELECT … WHERE id = %s\", (user_id,)).",
 ref:"CWE-89 · OWASP A03",
},
{
id:"S-SQL-JS", name:"SQL built from strings", type:"VULN", sev:"BLOCKER", langs:["js"],
 re:pyRe("\\.(query|execute)\\s*\\(\\s*(`[^`]*\\$\\{|\\\"[^\\\"]*\\\"\\s*\\+|'[^']*'\\s*\\+|\\w+\\s*\\+\\s*[\\\"'`])", ""),
 msg:"SQL query built with template literal or concatenation.",
 why:"Interpolating values into SQL enables SQL injection.",
 fix:"Use placeholders: db.query('SELECT … WHERE id = ?', [id]).",
 ref:"CWE-89 · OWASP A03",
},
{
id:"S-OSCMD-PY", name:"OS command execution", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("os\\.(system|popen)\\s*\\(", ""),
 msg:"os.system/os.popen runs shell commands.",
 why:"Any user-influenced portion of the command allows shell injection.",
 fix:"Use subprocess.run([...]) with a list of args and shell=False.",
 ref:"CWE-78 · OWASP A03",
},
{
id:"S-SHELL-TRUE", name:"subprocess with shell=True", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("shell\\s*=\\s*True", ""),
 msg:"shell=True passes the command through the shell.",
 why:"Shell metacharacters in user input become command injection.",
 fix:"Pass args as a list with shell=False.",
 ref:"CWE-78",
},
{
id:"S-EXEC-JS", name:"Shell exec", type:"HOTSPOT", sev:"CRITICAL", langs:["js"],
 re:pyRe("(?<![#$])(?<!\\bthis\\.)(?<!\\bself\\.)(?<!\\bsuper\\.)(?<!\\basync\\s)(?<!\\bstatic\\s)(?<!\\bget\\s)(?<!\\bset\\s)(?<!\\bfunction\\s)\\b(exec|execSync)\\s*\\((?![^()]*\\)\\s*\\{)\\s*(`[^`]*\\$\\{|[\\\"'][^\\\"']*[\\\"']\\s*\\+|\\w+\\s*[,)+])", ""),
 msg:"child_process exec with dynamic command string.",
 why:"Dynamic command strings passed to a shell risk command injection.",
 fix:"Use execFile/spawn with an argument array.",
 ref:"CWE-78 · OWASP A03",
},
{
id:"S-PICKLE", name:"Unsafe deserialization (pickle)", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("pickle\\.loads?\\s*\\(", ""),
 msg:"pickle.load(s) executes code embedded in the payload.",
 why:"Unpickling untrusted data is remote code execution by design.",
 fix:"Use JSON or another data-only format for untrusted input.",
 ref:"CWE-502 · OWASP A08",
},
{
id:"S-YAML", name:"Unsafe yaml.load", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("yaml\\.load\\s*\\((?!(?:(?!yaml\\.load)[^)])*(?:SafeLoader|safe_load))", ""),
 find:yamlLoadFind,
 msg:"yaml.load without SafeLoader can instantiate arbitrary objects.",
 why:"Full YAML loading executes constructors from the document.",
 fix:"Use yaml.safe_load() or Loader=yaml.SafeLoader.",
 ref:"CWE-502",
},
{
id:"S-SECRET", name:"Hardcoded credential", type:"VULN", sev:"BLOCKER", langs:["py", "js"],
 re:pyRe("(password|passwd|pwd|secret|api[_-]?key|access[_-]?key|auth[_-]?token|private[_-]?key)\\s*[:=]\\s*[\\\"'][^\\\"']{4,}[\\\"']", "i"),
 skip:pyRe("(environ|process\\.env|getenv|config\\[|\\bimport\\b|\\bplaceholder\\b|\\bexample\\b|\\bdummy\\b|\\bsample\\b|\\bmock\\b|\\bmocked\\b|\\bxxxx+\\b|\\{\\{)", "i"),
 msg:"Credential appears to be hardcoded in source.",
 why:"Secrets in code leak through version control, logs, and builds; rotation requires a deploy.",
 fix:"Load secrets from environment variables or a secrets manager, and rotate this one now.",
 ref:"CWE-798 · OWASP A07",
},
{
id:"S-WEAKHASH-PY", name:"Weak hash algorithm", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("hashlib\\.(md5|sha1)\\s*\\(", ""),
 msg:"MD5/SHA-1 are cryptographically broken.",
 why:"Collisions are practical; unusable for passwords or signatures.",
 fix:"Use SHA-256+ for integrity; bcrypt/scrypt/argon2 for passwords.",
 ref:"CWE-327/328",
},
{
id:"S-WEAKHASH-JS", name:"Weak hash algorithm", type:"VULN", sev:"MAJOR", langs:["js"],
 re:pyRe("createHash\\s*\\(\\s*[\\\"'](md5|sha1)[\\\"']", ""),
 msg:"MD5/SHA-1 are cryptographically broken.",
 why:"Collisions are practical; unusable for passwords or signatures.",
 fix:"Use sha256+ for integrity; bcrypt/scrypt/argon2 for passwords.",
 ref:"CWE-327/328",
},
{
id:"S-VERIFY", name:"TLS verification disabled", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("verify\\s*=\\s*False|_create_unverified_context", ""),
 msg:"Certificate verification is disabled.",
 why:"Disabling TLS verification allows trivial man-in-the-middle attacks.",
 fix:"Keep verify=True; add the internal CA to the trust store instead.",
 ref:"CWE-295 · OWASP A02",
},
{
id:"S-HTTP", name:"Cleartext HTTP URL", type:"HOTSPOT", sev:"MINOR", langs:["py", "js"],
 re:pyRe("[\\\"']http://(?!localhost|127\\.0\\.0\\.1|0\\.0\\.0\\.0)", ""),
 msg:"URL uses unencrypted http://.",
 why:"Data sent over HTTP can be read or altered in transit.",
 fix:"Use https:// unless this is a deliberate local/dev endpoint.",
 ref:"CWE-319 · OWASP A02",
},
{
id:"S-RANDOM", name:"Non-crypto randomness for secret", type:"HOTSPOT", sev:"MAJOR", langs:["py", "js"],
 re:pyRe("(random\\.(random|randint|choice|randrange|getrandbits)|Math\\.random)\\s*\\(", ""),
 need:pyRe("(token|secret|password|otp|nonce|session|key|reset|csrf)", "i"),
 msg:"PRNG used in a security-sensitive value.",
 why:"random/Math.random are predictable; generated tokens can be guessed.",
 fix:"Use secrets module (Python) or crypto.randomBytes / crypto.getRandomValues (JS).",
 ref:"CWE-338",
},
{
id:"S-INNERHTML", name:"HTML injection sink", type:"HOTSPOT", sev:"MAJOR", langs:["js"],
 re:pyRe("\\.(innerHTML|outerHTML)\\s*=|document\\.write\\s*\\(|insertAdjacentHTML\\s*\\(", ""),
 msg:"Assigning raw HTML — potential XSS sink.",
 why:"If the value contains user input, scripts can be injected into the page.",
 fix:"Use textContent, or sanitize with DOMPurify before inserting HTML.",
 ref:"CWE-79 · OWASP A03",
},
{
id:"S-DANGER", name:"dangerouslySetInnerHTML", type:"HOTSPOT", sev:"MAJOR", langs:["js"],
 re:pyRe("dangerouslySetInnerHTML", ""),
 msg:"React raw-HTML escape hatch in use.",
 why:"Bypasses React's XSS protection.",
 fix:"Render as text, or sanitize the HTML first.",
 ref:"CWE-79",
},
{
id:"S-TIMEOUT-STR", name:"setTimeout with string", type:"VULN", sev:"MAJOR", langs:["js"],
 re:pyRe("set(Timeout|Interval)\\s*\\(\\s*[\\\"'`]", ""),
 msg:"String argument to setTimeout/setInterval is implied eval.",
 why:"The string is compiled and executed like eval.",
 fix:"Pass a function reference instead.",
 ref:"CWE-95",
},
{
id:"S-LOCALSTORAGE", name:"Secret in localStorage", type:"HOTSPOT", sev:"MAJOR", langs:["js"],
 re:pyRe("localStorage\\.setItem\\s*\\(\\s*[\\\"'][^\\\"']*(token|jwt|password|secret|auth)", "i"),
 msg:"Sensitive value stored in localStorage.",
 why:"localStorage is readable by any script on the page (XSS steals it).",
 fix:"Prefer httpOnly cookies for session tokens.",
 ref:"CWE-522",
},
{
id:"S-JWT-NONE", name:"JWT 'none' algorithm", type:"VULN", sev:"BLOCKER", langs:["js", "py"],
 re:pyRe("algorithms?\\s*[:=]\\s*\\[?\\s*[\\\"']none[\\\"']", "i"),
 msg:"JWT verification accepts the 'none' algorithm.",
 why:"Attackers can forge unsigned tokens that pass verification.",
 fix:"Pin an explicit algorithm list, e.g. ['HS256'] or ['RS256'].",
 ref:"CWE-347",
},
{
id:"S-CORS", name:"CORS wildcard", type:"HOTSPOT", sev:"MAJOR", langs:["js", "py"],
 re:pyRe("Access-Control-Allow-Origin[\\\"']?\\s*[,:]\\s*[\\\"']\\*", ""),
 msg:"CORS allows all origins.",
 why:"Any website can call this API with the user's credentials context.",
 fix:"Whitelist specific origins.",
 ref:"OWASP A05",
},
{
id:"S-DEBUG", name:"Debug mode enabled", type:"HOTSPOT", sev:"MAJOR", langs:["py"],
 re:pyRe("debug\\s*=\\s*True", ""),
 msg:"debug=True — never in production.",
 why:"Flask/Django debug mode exposes an interactive console and stack traces.",
 fix:"Drive debug from an environment variable, defaulting to off.",
 ref:"CWE-489 · OWASP A05",
},
{
id:"S-BIND-ALL", name:"Binding to all interfaces", type:"HOTSPOT", sev:"MINOR", langs:["py", "js"],
 re:pyRe("[\\\"']0\\.0\\.0\\.0[\\\"']", ""),
 msg:"Service binds to 0.0.0.0 (all interfaces).",
 why:"Exposes the service on every network interface, including public ones.",
 fix:"Bind to 127.0.0.1 unless external access is intended.",
 ref:"CWE-668",
},
{
id:"S-MKTEMP", name:"Insecure temp file", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("tempfile\\.mktemp\\s*\\(", ""),
 msg:"tempfile.mktemp is race-condition prone.",
 why:"The name can be claimed by an attacker between creation and use.",
 fix:"Use tempfile.NamedTemporaryFile or mkstemp.",
 ref:"CWE-377",
},
{
id:"B-BARE-EXCEPT", name:"Bare except", type:"BUG", sev:"MAJOR", langs:["py"],
 re:pyRe("^\\s*except\\s*:", ""),
 msg:"Bare except: catches everything, including SystemExit/KeyboardInterrupt.",
 why:"Hides real failures and makes the process unkillable.",
 fix:"Catch the specific exception types you expect.",
 ref:"Reliability",
},
{
id:"B-EQEQ", name:"Loose equality", type:"BUG", sev:"MINOR", langs:["js"],
 re:pyRe("[^=!<>]==[^=]|[^!]!=[^=]", ""),
 skip:pyRe("^\\s*(//|\\*|/\\*)", "i"),
 msg:"== / != perform type coercion.",
 why:"'' == 0 is true; coercion causes subtle logic bugs.",
 fix:"Use === and !==.",
 ref:"Reliability",
},
{
id:"Q-TODO", name:"TODO/FIXME marker", type:"SMELL", sev:"INFO", langs:["py", "js", "sql"],
 re:pyRe("\\b(TODO|FIXME|XXX|HACK)\\b", ""),
 msg:"Unresolved TODO/FIXME comment.",
 why:"Tracked work living only in comments tends to be forgotten.",
 fix:"File a ticket and link it, or resolve it.",
 ref:"Maintainability",
},
{
id:"Q-CONSOLE", name:"console.log left in code", type:"SMELL", sev:"MINOR", langs:["js"],
 re:pyRe("console\\.(log|debug)\\s*\\(", ""),
 msg:"Debug logging left in code.",
 why:"Noisy output and possible data leakage in production.",
 fix:"Remove, or use a leveled logger.",
 ref:"Maintainability",
},
{
id:"Q-VAR", name:"var declaration", type:"SMELL", sev:"MINOR", langs:["js"],
 re:pyRe("\\bvar\\s+[A-Za-z_$]", ""),
 msg:"var is function-scoped and hoisted.",
 why:"Block-scoped declarations prevent shadowing bugs.",
 fix:"Use let or const.",
 ref:"Maintainability",
},
{
id:"S-TOKEN", name:"Known secret token format", type:"VULN", sev:"BLOCKER", langs:["py", "js"],
 re:pyRe("AKIA[0-9A-Z]{16}|gh[pousr]_[A-Za-z0-9]{36}|xox[baprs]-[A-Za-z0-9-]{10,}|sk_live_[A-Za-z0-9]{16,}|AIza[0-9A-Za-z_\\-]{35}|-----BEGIN [A-Z ]*PRIVATE KEY-----|eyJ[A-Za-z0-9_\\-]{10,}\\.eyJ[A-Za-z0-9_\\-]{10,}", ""),
 find:(line) => { const t = findSecretToken(line); return t ? t.index : -1; },
 msg:"String matches a known secret format (AWS/GitHub/Slack/Stripe/Google key, private key, or JWT).",
 why:"Provider-format tokens in source are live credentials until proven otherwise.",
 fix:"Remove it, rotate the credential immediately, and load it from a secrets manager.",
 ref:"CWE-798 · OWASP A07",
},
{
id:"S-BIDI", name:"Trojan Source bidi control", type:"VULN", sev:"CRITICAL", langs:["py", "js", "sql"],
 re:pyRe("[\\u202a-\\u202e\\u2066-\\u2069]", ""),
 msg:"Bidirectional control character in source (Trojan Source)",
 why:"Bidi override and isolate characters make code display in a different order than the compiler reads it, so reviewers approve logic that is not what runs (CVE-2021-42574).",
 fix:"Remove the control characters; where a string really needs one, write it as an escape sequence (e.g. \\u202e) so it is visible.",
 ref:"CWE-451 · CVE-2021-42574",
},
{
id:"S-SSTI", name:"Template injection risk", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("render_template_string\\s*\\(\\s*(?![\\\"'])", ""),
 msg:"render_template_string with a non-literal template.",
 why:"User input compiled as a Jinja2 template is server-side template injection → RCE.",
 fix:"Pass data as template parameters; never build template source from input.",
 ref:"CWE-1336 · OWASP A03",
},
{
id:"S-XML", name:"XML parsing without a hardened parser", type:"HOTSPOT", sev:"MINOR", langs:["py"],
 re:pyRe("(?:^|\\s)(?:import\\s+xml\\.(?:etree|dom|sax)|from\\s+xml\\.(?:etree|dom|sax))", ""),
 msg:"Stdlib XML parsers are unsafe for untrusted input.",
 why:"xml.etree/dom/sax are vulnerable to entity-expansion and (historically) XXE attacks.",
 fix:"Parse untrusted XML with a hardened parser such as defusedxml or lazaret.safexml.",
 ref:"CWE-611",
},
{
id:"S-MARKSAFE", name:"mark_safe usage", type:"HOTSPOT", sev:"MAJOR", langs:["py"],
 re:pyRe("mark_safe\\s*\\(", ""),
 msg:"mark_safe bypasses Django's HTML escaping.",
 why:"If the value contains user input, this is an XSS vector.",
 fix:"Escape user data; use format_html for building markup.",
 ref:"CWE-79",
},
{
id:"S-AUTOESCAPE", name:"Template autoescape disabled", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("autoescape\\s*=\\s*False", ""),
 msg:"Template autoescaping is turned off.",
 why:"Every rendered variable becomes a potential XSS vector.",
 fix:"Leave autoescape on; mark trusted fragments individually.",
 ref:"CWE-79",
},
{
id:"S-PARAMIKO", name:"SSH host key verification disabled", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("AutoAddPolicy|WarningPolicy", ""),
 msg:"SSH host keys accepted without verification.",
 why:"Enables man-in-the-middle attacks on SSH connections.",
 fix:"Use RejectPolicy with a managed known_hosts file.",
 ref:"CWE-295",
},
{
id:"S-CLEARTEXT-PROTO", name:"Cleartext protocol module", type:"HOTSPOT", sev:"MINOR", langs:["py"],
 re:pyRe("(?:^|\\s)(?:import\\s+(?:telnetlib|ftplib)|from\\s+(?:telnetlib|ftplib))", ""),
 msg:"Telnet/FTP transmit credentials in cleartext.",
 why:"Anyone on the network path can capture the credentials.",
 fix:"Use SSH/SFTP (e.g. paramiko) instead.",
 ref:"CWE-319",
},
{
id:"S-CHMOD", name:"Overly permissive file mode", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("chmod\\s*\\([^,()]*,\\s*0o?7[67]7", ""),
 find:chmodFind,
 msg:"File made world-writable (777/767).",
 why:"Any local user or process can modify the file.",
 fix:"Use the least permissive mode that works (e.g. 0o600/0o644).",
 ref:"CWE-732",
},
{
id:"S-WEAKCIPHER-PY", name:"Weak cipher or mode", type:"VULN", sev:"MAJOR", langs:["py"],
 re:pyRe("\\b(?:DES|DES3|ARC4|Blowfish)\\.new|MODE_ECB", ""),
 msg:"DES/RC4/Blowfish/ECB are cryptographically weak.",
 why:"These ciphers/modes are breakable or leak plaintext structure.",
 fix:"Use AES-GCM (cryptography library, AESGCM).",
 ref:"CWE-327",
},
{
id:"S-WEAKCIPHER-JS", name:"Weak cipher", type:"VULN", sev:"MAJOR", langs:["js"],
 re:pyRe("createCipheriv\\s*\\(\\s*[\\\"'](?:des|des-ede3?|rc4|aes-\\d+-ecb)", "i"),
 msg:"DES/RC4/ECB are cryptographically weak.",
 why:"These ciphers/modes are breakable or leak plaintext structure.",
 fix:"Use aes-256-gcm.",
 ref:"CWE-327",
},
{
id:"S-PROTO", name:"Prototype pollution sink", type:"VULN", sev:"MAJOR", langs:["js"],
 re:pyRe("\\[\\s*[\\\"']__proto__[\\\"']\\s*\\]|\\.__proto__\\s*[=.[]|constructor\\s*\\[\\s*[\\\"']prototype[\\\"']\\s*\\]", ""),
 msg:"Write access to __proto__/prototype.",
 why:"Attacker-controlled keys can pollute Object.prototype and change app behavior globally.",
 fix:"Block __proto__/constructor/prototype keys in merges; use Object.create(null) maps.",
 ref:"CWE-1321",
},
{
id:"S-NOSQL", name:"MongoDB $where operator", type:"VULN", sev:"MAJOR", langs:["js"],
 re:pyRe("\\$where", ""),
 msg:"$where evaluates JavaScript inside the database.",
 why:"User input in $where is NoSQL injection with code execution.",
 fix:"Use query operators ($eq, $in, …) instead.",
 ref:"CWE-943",
},
{
id:"S-VM-JS", name:"vm module code execution", type:"HOTSPOT", sev:"MAJOR", langs:["js"],
 re:pyRe("vm\\.runIn(?:New|This)?Context|require\\s*\\(\\s*[\\\"']vm[\\\"']", ""),
 msg:"Node vm module is not a security sandbox.",
 why:"Code can escape the vm context and reach the host process.",
 fix:"Don't run untrusted code in-process; use isolated workers/containers.",
 ref:"CWE-94",
},
{
id:"S-SPAWN-SHELL", name:"child_process with shell:true", type:"VULN", sev:"CRITICAL", langs:["js"],
 re:pyRe("shell\\s*:\\s*true", ""),
 msg:"shell:true routes the command through a shell.",
 why:"Shell metacharacters in arguments become command injection.",
 fix:"Use execFile/spawn with an args array and shell:false.",
 ref:"CWE-78",
},
{
id:"SC-EVAL-DECODE", name:"Decoded payload execution", type:"VULN", sev:"BLOCKER", langs:["py", "js"],
 re:pyRe("\\b(?:eval|exec|execSync|Function|runIn(?:This|New)?Context)\\s*\\(\\s*(?:compile\\s*\\(\\s*)?(?:(?:[\\w$]+|__import__\\(\\s*['\\\"][\\w.]+['\\\"]\\s*\\)|importlib\\.import_module\\(\\s*['\\\"][\\w.]+['\\\"]\\s*\\))\\s*\\.\\s*)*(?:atob|unescape|decodeURIComponent|Buffer\\s*\\.\\s*from|b64decode|(?:codecs|__import__\\(\\s*['\\\"]codecs['\\\"]\\s*\\)|importlib\\.import_module\\(\\s*['\\\"]codecs['\\\"]\\s*\\))\\s*\\.\\s*decode|(?:zlib|__import__\\(\\s*['\\\"]zlib['\\\"]\\s*\\)|importlib\\.import_module\\(\\s*['\\\"]zlib['\\\"]\\s*\\))\\s*\\.\\s*decompress|(?:marshal|__import__\\(\\s*['\\\"]marshal['\\\"]\\s*\\)|importlib\\.import_module\\(\\s*['\\\"]marshal['\\\"]\\s*\\))\\s*\\.\\s*loads|fromhex|unhexlify)\\s*\\(", ""),
 msg:"Code decoded (base64/escape) and immediately executed.",
 why:"Decode-then-execute is the signature pattern of malware droppers and supply-chain implants.",
 fix:"Treat as hostile until proven otherwise; inspect the decoded payload.",
 ref:"CWE-506 · Supply chain",
},
{
id:"SC-PACKER", name:"Packed JavaScript (p,a,c,k,e,d)", type:"VULN", sev:"CRITICAL", langs:["js"],
 re:pyRe("eval\\s*\\(\\s*function\\s*\\(\\s*p\\s*,\\s*a\\s*,\\s*c\\s*,\\s*k\\s*,\\s*e", ""),
 msg:"Dean Edwards packer signature — self-decoding packed code.",
 why:"Legitimate modern packages ship minified, not packed; packing hides intent.",
 fix:"Unpack and review the payload before trusting this file.",
 ref:"CWE-506 · Supply chain",
},
{
id:"SC-MARSHAL", name:"Marshalled bytecode execution", type:"VULN", sev:"CRITICAL", langs:["py"],
 re:pyRe("\\bmarshal\\s*\\.\\s*loads?\\s*\\(|['\\\"]marshal['\\\"]\\s*\\)\\s*\\.\\s*loads?\\s*\\(|\\b(?:types\\s*\\.\\s*)?CodeType\\s*\\(|\\bimp\\s*\\.\\s*load_compiled\\s*\\(|\\bSourcelessFileLoader\\s*\\(", ""),
 msg:"Loading marshalled bytecode or building a code object by hand.",
 why:"Bytecode blobs evade source review — a common Python malware technique.",
 fix:"Inspect the blob's origin; refuse opaque executable data in source trees.",
 ref:"CWE-506 · Supply chain",
},
{
id:"SQL-XPCMD", name:"OS command execution via SQL", type:"VULN", sev:"CRITICAL", langs:["sql"],
 re:pyRe("\\bxp_cmdshell\\b", "i"),
 msg:"xp_cmdshell runs operating-system commands from SQL Server.",
 why:"Enables full OS command execution from the database; a top post-exploitation target.",
 fix:"Keep xp_cmdshell disabled; use a vetted, sandboxed job runner instead.",
 ref:"CWE-78 · OWASP A03",
},
{
id:"SQL-DYNAMIC", name:"Dynamic SQL from concatenation", type:"VULN", sev:"BLOCKER", langs:["sql"],
 re:pyRe("EXEC(?:UTE)?\\s*\\(\\s*@?\\w+\\s*\\+|EXECUTE\\s+IMMEDIATE\\b(?:(?!EXECUTE\\s+IMMEDIATE\\b)[^;])*\\|\\||sp_executesql\\b(?:(?!sp_executesql\\b)[^;])*\\+|EXEC\\s*\\(\\s*['\\\"][^']*['\\\"]\\s*\\+|SET\\s+@\\w+\\s*=(?:(?!SET\\s+@)[^;'\\\"])*['\\\"](?:(?!SET\\s+@)[^;])*(?:\\+|\\|\\|)", "i"),
 find:sqlDynamicFind,
 msg:"Dynamic SQL built by concatenating variables into the statement.",
 why:"String-built SQL executed with EXEC / EXECUTE IMMEDIATE / sp_executesql is SQL injection inside the database.",
 fix:"Use parameterized dynamic SQL (sp_executesql with @params, or bind variables).",
 ref:"CWE-89 · OWASP A03",
},
{
id:"SQL-CRED", name:"Hardcoded database credential", type:"VULN", sev:"BLOCKER", langs:["sql"],
 re:pyRe("(?:IDENTIFIED\\s+BY\\s+['\\\"][^'\\\"]+['\\\"]|PASSWORD\\s*=?\\s*['\\\"][^'\\\"]+['\\\"]|IDENTIFIED\\s+BY\\s+PASSWORD)", "i"),
 skip:pyRe("\\bplaceholder\\b|\\bexample\\b|\\bdummy\\b|\\bmock\\b|\\bxxxx+\\b", "i"),
 msg:"Credential embedded in a SQL script.",
 why:"Passwords in DDL scripts leak through version control and backups.",
 fix:"Provision credentials out-of-band (secrets manager / vault), not in checked-in SQL.",
 ref:"CWE-798 · OWASP A07",
},
{
id:"SQL-GRANT-ALL", name:"Excessive privilege grant", type:"HOTSPOT", sev:"MAJOR", langs:["sql"],
 re:pyRe("\\bGRANT\\s+ALL\\b|\\bWITH\\s+GRANT\\s+OPTION\\b", "i"),
 msg:"GRANT ALL / WITH GRANT OPTION hands over broad privileges.",
 why:"Violates least privilege; a compromised account inherits everything.",
 fix:"Grant only the specific privileges the role needs.",
 ref:"CWE-732 · OWASP A01",
},
{
id:"SQL-GRANT-PUBLIC", name:"Grant to PUBLIC", type:"HOTSPOT", sev:"MAJOR", langs:["sql"],
 re:pyRe("\\bGRANT\\b(?:(?!\\bGRANT\\b)[^;])*\\bTO\\s+PUBLIC\\b", "i"),
 find:grantPublicFind,
 msg:"Privilege granted to PUBLIC (every user).",
 why:"PUBLIC grants apply to all current and future accounts, including low-trust ones.",
 fix:"Grant to a specific role instead of PUBLIC.",
 ref:"CWE-732 · OWASP A01",
},
{
id:"SQL-FILE", name:"Filesystem access from SQL", type:"VULN", sev:"CRITICAL", langs:["sql"],
 re:pyRe("\\bINTO\\s+(?:OUTFILE|DUMPFILE)\\b|\\bLOAD_FILE\\s*\\(|\\bLOAD\\s+DATA\\s+INFILE\\b", "i"),
 msg:"SQL reads/writes the server filesystem (OUTFILE / LOAD_FILE).",
 why:"A classic data-exfiltration and webshell-drop primitive in SQL injection exploitation.",
 fix:"Disable FILE privilege; never build these paths from untrusted input.",
 ref:"CWE-73 · OWASP A03",
},
{
id:"SQL-OPENROWSET", name:"Ad-hoc remote data access", type:"HOTSPOT", sev:"MAJOR", langs:["sql"],
 re:pyRe("\\b(?:OPENROWSET|OPENQUERY|OPENDATASOURCE)\\s*\\(", "i"),
 msg:"OPENROWSET/OPENQUERY perform ad-hoc external connections.",
 why:"Can reach arbitrary hosts/files and is abused for lateral movement.",
 fix:"Disable Ad Hoc Distributed Queries; use configured linked servers with least privilege.",
 ref:"CWE-610",
},
{
id:"SQL-FK-OFF", name:"Integrity checks disabled", type:"HOTSPOT", sev:"MAJOR", langs:["sql"],
 re:pyRe("SET\\s+FOREIGN_KEY_CHECKS\\s*=\\s*0|NOCHECK\\s+CONSTRAINT|SET\\s+CONSTRAINTS\\s+ALL\\s+DEFERRED", "i"),
 msg:"Referential-integrity enforcement is turned off.",
 why:"Disabling constraints allows orphaned/inconsistent data to be written.",
 fix:"Re-enable checks immediately after the bulk operation; scope it tightly.",
 ref:"CWE-20",
},
{
id:"SQL-TRUSTWORTHY", name:"TRUSTWORTHY database", type:"HOTSPOT", sev:"MAJOR", langs:["sql"],
 re:pyRe("SET\\s+TRUSTWORTHY\\s+ON", "i"),
 msg:"TRUSTWORTHY ON enables privilege escalation paths in SQL Server.",
 why:"Combined with impersonation it can lead to sysadmin escalation.",
 fix:"Leave TRUSTWORTHY OFF; sign modules instead.",
 ref:"CWE-269",
},
{
id:"SQL-NOLOCK", name:"Dirty-read hint", type:"SMELL", sev:"MINOR", langs:["sql"],
 re:pyRe("WITH\\s*\\(\\s*NOLOCK\\s*\\)|READ\\s+UNCOMMITTED", "i"),
 msg:"NOLOCK / READ UNCOMMITTED permits dirty reads.",
 why:"Returns uncommitted, possibly inconsistent data; a common source of subtle bugs.",
 fix:"Use an appropriate isolation level (e.g. READ COMMITTED SNAPSHOT).",
 ref:"Reliability",
},
{
id:"SQL-SELECT-STAR", name:"SELECT *", type:"SMELL", sev:"MINOR", langs:["sql"],
 re:pyRe("\\bSELECT\\s+\\*", "i"),
 msg:"SELECT * fetches all columns.",
 why:"Breaks silently on schema changes and moves unneeded data.",
 fix:"List the columns you actually need.",
 ref:"Maintainability",
},
];
export const TEXT_RULES = [
{
id:"B-EMPTY-CATCH", name:"Empty catch block", type:"BUG", sev:"MAJOR", langs:["js"],
 re:pyRe("catch\\s*(\\([^()]*\\))?\\s*\\{\\s*\\}", ""),
 scan:emptyCatchScan,
 msg:"Exception swallowed by empty catch.",
 why:"Errors vanish silently, making failures undiagnosable.",
 fix:"Handle the error or at least log it.",
 ref:"Reliability",
},
{
id:"B-EXCEPT-PASS", name:"except: pass", type:"BUG", sev:"MAJOR", langs:["py"],
 re:pyRe("except(?:(?!except)[^\\n:])*:[^\\S\\n]*\\n\\s*pass\\b", ""),
 scan:exceptPassScan,
 msg:"Exception swallowed with pass.",
 why:"Errors vanish silently, making failures undiagnosable.",
 fix:"Handle the error or at least log it.",
 ref:"Reliability",
},
{
id:"SQL-DELETE-NOWHERE", name:"DELETE without WHERE", type:"BUG", sev:"MAJOR", langs:["sql"],
 re:pyRe("\\bDELETE\\s+FROM\\s+[\\w.\\\"\\[\\]`]+", "i"),
 nowhere:true, // fired by scanSqlNowhere (sql.js), linear
 msg:"DELETE has no WHERE clause — it removes every row.",
 why:"An unqualified DELETE wipes the whole table; usually a mistake outside teardown scripts.",
 fix:"Add a WHERE clause, or use TRUNCATE deliberately if a full wipe is intended.",
 ref:"CWE-665",
},
{
id:"SQL-UPDATE-NOWHERE", name:"UPDATE without WHERE", type:"BUG", sev:"MAJOR", langs:["sql"],
 re:pyRe("\\bUPDATE\\s+[\\w.\\\"\\[\\]`]+\\s+SET\\b", "i"),
 nowhere:true,
 msg:"UPDATE has no WHERE clause — it changes every row.",
 why:"An unqualified UPDATE rewrites the entire table.",
 fix:"Add a WHERE clause to scope the update.",
 ref:"CWE-665",
},
];
