#!/usr/bin/env python3
"""The Rust engine's data: the Unicode tables, and the rule pack's checks.

    python3.10 scripts/make_rust_tables.py          # rewrite the Unicode tables; reformat the pack
    python3 scripts/make_rust_tables.py --check     # exit 1 if either is stale or the pack is wrong

* rust/crates/lazaret-engine/rules/lazaret-rules.json, the rule pack: the
  engine's patterns (their text and flags, in Python's `re` syntax, which the
  engine's regex engines read), name sets, tables, limits and finding texts.
  Since the Rust-first refactor it is the source: it was extracted from
  lazaret.scanner.core, whose detectors it served, and core no longer holds
  them. Edit it by hand; this script writes it back in its canonical form
  (sorted keys, one space of indent, ASCII), and --check fails when it is
  not in that form, when its rule set is not the registry's ENGINE_VERSION,
  when a pattern does not compile with Python's re, when a value core
  still holds differs from the pack's (core keeps the few the Python side
  reads itself: reasons the registry ranks, limits the walk applies), or
  when live secret verification's provider table (_VERIFY_PROVIDERS) breaks
  the rules of lazaret.scanner.secretverify.validate.

* rust/crates/lazaret-engine/src/generated/unicode13.rs: the character data
  the engine reads source text with, from Unicode 13.0 (Python 3.10's
  unicodedata, the oldest supported, which the scanner pins source text to:
  lazaret/scanner/_unicode13.py). What Python's `re` and `str` use: \\w
  (isalnum), \\d (isdecimal), \\s (isspace), the simple case mappings sre
  folds with, the full case mappings and the Final_Sigma context of
  str.lower(), re's extra case equivalences (s and ſ, µ and μ, …), printable and
  identifier characters. Only Python 3.10 writes it; on any other Python,
  --check verifies that every code point Unicode 13.0 assigns reads the same
  there for the properties the scanner relies on (STABLE), and that the table
  holds nothing for the ones Unicode 13.0 leaves unassigned.
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(REPO, "rust", "crates", "lazaret-engine", "src", "generated")
UNICODE_OUT = os.path.join(GEN, "unicode13.rs")
PACK_OUT = os.path.join(REPO, "rust", "crates", "lazaret-engine", "rules", "lazaret-rules.json")
sys.path.insert(0, os.path.join(REPO, "python", "src"))

MAX_CP = 0x110000
HEADER = "// Generated by scripts/make_rust_tables.py from {src} — do not edit.\n"
# unicode13.rs is Unicode data (rust/NOTICE): its notice travels with it
UNICODE_NOTICE = ("//\n// Data of the Unicode Character Database 13.0, distributed under the Unicode\n"
                  "// License v3 (rust/LICENSE-UNICODE):\n//   Copyright © 1991-2026 Unicode, Inc.\n")

# ---- property bits (crates/lazaret-engine/src/unicode.rs names them) ----
ALNUM, DECIMAL, DIGIT, SPACE, ALPHA, LINEBREAK, CASED, CASE_IGNORABLE = (1 << i for i in range(8))
PRINTABLE, NUMERIC, ID_START, ID_CONTINUE, UPPER, LOWER, TITLE = (1 << i for i in range(8, 15))


def _linebreaks():
    """Py_UNICODE_ISLINEBREAK: the characters str.splitlines() splits at."""
    return frozenset(c for c in range(MAX_CP) if len(("a" + chr(c) + "b").splitlines()) == 2)


def props(c, linebreaks):
    """The property bits of code point c on this Python."""
    ch = chr(c)
    f = 0
    if ch.isalnum():
        f |= ALNUM
    if ch.isdecimal():
        f |= DECIMAL
    if ch.isdigit():
        f |= DIGIT
    if ch.isspace():
        f |= SPACE
    if ch.isalpha():
        f |= ALPHA
    if c in linebreaks:
        f |= LINEBREAK
    # str.lower()'s Final_Sigma context reads Cased and Case_Ignorable, which
    # Python does not expose; they are read back from lower() itself. A
    # case-ignorable character is skipped whatever else it is, so CASED is
    # the property of a character that is not case-ignorable:
    #   ("A" + ch + "Σ") is final  <=>  ch is case-ignorable or cased
    #   (ch + "Σ") is final        <=>  ch is not case-ignorable and cased
    t1 = ("A" + ch + "Σ").lower()[-1] == "ς"
    t2 = (ch + "Σ").lower()[-1] == "ς"
    if t2:
        f |= CASED
    if t1 and not t2:
        f |= CASE_IGNORABLE
    if ch.isprintable():
        f |= PRINTABLE
    if ch.isnumeric():
        f |= NUMERIC
    if ch.isidentifier():
        f |= ID_START
    if ("a" + ch).isidentifier():
        f |= ID_CONTINUE
    if ch.isupper():
        f |= UPPER
    if ch.islower():
        f |= LOWER
    if ch.istitle():
        f |= TITLE
    return f


def sre_lower(c):
    import _sre
    return _sre.unicode_tolower(c)


def sre_upper(c):
    """_PyUnicode_ToUppercase: the simple mapping, or the first character of
    the full one for a character SpecialCasing lists (what sre's
    RANGE_UNI_IGNORE reads)."""
    u = chr(c).upper()
    return ord(u[0]) if u else c


def case_fixes():
    """re's extra case equivalences, from Unicode's case mappings: the
    lowercase letters that share an uppercase with another lowercase letter
    (s and ſ, both S; µ and μ; the Greek letters' variant forms), each ->
    the others in code point order. Unicode 13.0's letters only, whatever
    this Python's Unicode; --check holds the result to re's own table."""
    from lazaret.scanner import _unicode13
    lows_by_upper = {}
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            continue
        low = chr(c).lower()
        if len(low) == 1:
            lows_by_upper.setdefault(chr(c).upper(), set()).add(ord(low))
    fixes = {}
    for lows in lows_by_upper.values():
        if len(lows) > 1:
            for c in lows:
                fixes[c] = tuple(sorted(lows - {c}))
    return fixes


def check_case_fixes():
    """The equivalences re itself adds under IGNORECASE (re._casefix on
    3.11 and later, sre_compile's table on 3.10) are case_fixes()'s."""
    try:
        from re._casefix import _EXTRA_CASES as res                # 3.11+
    except ImportError:
        import sre_compile                                        # 3.10
        res = sre_compile._ignorecase_fixes
    if {k: tuple(sorted(v)) for k, v in res.items()} != case_fixes():
        return ["re's extra case equivalences are not the lowercase letters that share an uppercase"]
    return []


def unicode_data():
    """Everything unicode13.rs holds, from this Python."""
    lb = _linebreaks()
    flags = [props(c, lb) for c in range(MAX_CP)]
    lower = {c: sre_lower(c) for c in range(MAX_CP) if sre_lower(c) != c}
    upper = {c: sre_upper(c) for c in range(MAX_CP) if sre_upper(c) != c}
    full_lower = {}
    for c in range(MAX_CP):
        if c == 0x3A3:
            continue                              # Σ: its context decides (unicode.rs)
        low = chr(c).lower()
        if len(low) != 1 or ord(low) != lower.get(c, c):
            full_lower[c] = [ord(x) for x in low]
    full_upper = {}
    for c in range(MAX_CP):
        up = chr(c).upper()
        if len(up) != 1 or ord(up) != upper.get(c, c):
            full_upper[c] = [ord(x) for x in up]
    # str.casefold() where it is not str.lower() of the character alone (Σ's alone is σ, its fold too)
    full_fold = {c: [ord(x) for x in chr(c).casefold()] for c in range(MAX_CP) if chr(c).casefold() != chr(c).lower()}
    import unicodedata
    decimal_runs = []                              # (first, last, value of first): int() of a digit
    for ch in range(MAX_CP):
        if flags[ch] & DECIMAL:
            v = unicodedata.decimal(chr(ch))
            if decimal_runs and decimal_runs[-1][1] == ch - 1 and \
                    decimal_runs[-1][2] + (ch - decimal_runs[-1][0]) == v:
                decimal_runs[-1][1] = ch
            else:
                decimal_runs.append([ch, ch, v])
    return {"flags": flags, "lower": lower, "upper": upper, "full_lower": full_lower,
            "full_upper": full_upper, "full_fold": full_fold, "fixes": case_fixes(), "decimal_runs": decimal_runs,
            **normalization_data()}


HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3         # syllables: decomposed and composed by arithmetic
#                                                 # (3.13's unicodedata.decomposition lists them, 3.10's not)


def normalization_data():
    """What unicodedata.normalize reads, from this Python: each code point's
    decomposition, one level (unicodedata.decomposition: canonical, or a
    compatibility mapping; Hangul syllables are computed, not listed), the
    canonical combining classes, and the primary composites (a canonical
    decomposition into two characters, the first a starter, that is not
    excluded from composition: NFC gives the character back)."""
    import unicodedata
    decomp, ccc_runs = {}, []                      # cp -> (compatibility?, [cp, …]); [first, last, class]
    for c in range(MAX_CP):
        ch = chr(c)
        d = unicodedata.decomposition(ch) if not HANGUL_FIRST <= c <= HANGUL_LAST else ""
        if d:
            parts = d.split()
            compat = parts[0].startswith("<")
            decomp[c] = (compat, [int(x, 16) for x in (parts[1:] if compat else parts)])
        k = unicodedata.combining(ch)
        if k:
            if ccc_runs and ccc_runs[-1][1] == c - 1 and ccc_runs[-1][2] == k:
                ccc_runs[-1][1] = c
            else:
                ccc_runs.append([c, c, k])
    compose = sorted((parts[0], parts[1], c) for c, (compat, parts) in decomp.items()
                     if not compat and len(parts) == 2 and not unicodedata.combining(chr(parts[0]))
                     and unicodedata.normalize("NFC", chr(c)) == chr(c))
    return {"decomp": decomp, "ccc_runs": ccc_runs, "compose": compose}


def render_unicode(data):
    from lazaret.scanner import _unicode13
    runs = []
    prev = None
    for c, f in enumerate(data["flags"]):
        if f != prev:
            runs.append((c, f))
            prev = f
    out = [HEADER.format(src="Python 3.10's unicodedata (Unicode 13.0.0)"),
           UNICODE_NOTICE,
           "#![allow(clippy::unreadable_literal)]\n\n",
           "/// Lengths of alternating runs from U+0000: assigned, unassigned, … (_unicode13.RUNS).\n",
           "pub const ASSIGNED_RUNS: &[u32] = &[",
           ", ".join(str(int(t, 36)) for t in _unicode13.RUNS.split()), "];\n\n",
           "/// (first code point, property bits) of each run of equal properties.\n",
           f"pub const PROPS: &[(u32, u16)] = &[\n"]
    for i in range(0, len(runs), 8):
        out.append("    " + " ".join(f"(0x{c:X}, 0x{f:X})," for c, f in runs[i:i + 8]) + "\n")
    out.append("];\n\n")

    def pairs(name, doc, table):
        out.append(f"/// {doc}\n")
        out.append(f"pub const {name}: &[(u32, u32)] = &[\n")
        items = sorted(table.items())
        for i in range(0, len(items), 8):
            out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X})," for a, b in items[i:i + 8]) + "\n")
        out.append("];\n\n")

    def lists(name, doc, table):
        out.append(f"/// {doc}\n")
        out.append(f"pub const {name}: &[(u32, &[u32])] = &[\n")
        for a, bs in sorted(table.items()):
            out.append(f"    (0x{a:X}, &[" + ", ".join(f"0x{b:X}" for b in bs) + "]),\n")
        out.append("];\n\n")

    pairs("LOWER", "sre's simple lowercase (_sre.unicode_tolower) where it is not the character itself.",
          data["lower"])
    pairs("UPPER", "sre's uppercase (_PyUnicode_ToUppercase) where it is not the character itself.",
          data["upper"])
    lists("FULL_LOWER", "str.lower() where it is not LOWER's one character (Σ excepted: its context decides).",
          data["full_lower"])
    lists("FULL_UPPER", "str.upper() where it is not UPPER's one character.", data["full_upper"])
    lists("FULL_FOLD", "str.casefold() where it is not the character's str.lower() (FULL_LOWER's, or LOWER's one "
          "character).", data["full_fold"])
    lists("CASE_FIXES", "re's extra case equivalences: lowercase letters that share an uppercase -> the others.",
          data["fixes"])
    out.append("/// (first, last, value of first) of each run of decimal digits: int() reads them.\n")
    out.append("pub const DECIMAL_RUNS: &[(u32, u32, u32)] = &[\n")
    runs = data["decimal_runs"]
    for i in range(0, len(runs), 6):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, {v})," for a, b, v in runs[i:i + 6]) + "\n")
    out.append("];\n\n")
    render_normalization(out, data)
    return "".join(out)


def render_normalization(out, data):
    out.append("/// (first, last, class) of each run of code points with the same canonical combining class\n"
               "/// (unicodedata.combining), those with a class other than 0.\n")
    out.append("pub const CCC_RUNS: &[(u32, u32, u8)] = &[\n")
    runs = data["ccc_runs"]
    for i in range(0, len(runs), 6):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, {k})," for a, b, k in runs[i:i + 6]) + "\n")
    out.append("];\n\n")
    flat, index = [], []
    for c, (compat, parts) in sorted(data["decomp"].items()):
        index.append((c, len(flat), len(parts) | (0x80 if compat else 0)))
        flat.extend(parts)
    out.append("/// Each decomposition, one level (unicodedata.decomposition; Hangul syllables are computed):\n"
               "/// (code point, start in DECOMP_DATA, length, + 0x80 for a compatibility mapping).\n")
    out.append("pub const DECOMP: &[(u32, u16, u8)] = &[\n")
    for i in range(0, len(index), 6):
        out.append("    " + " ".join(f"(0x{c:X}, {at}, 0x{n:X})," for c, at, n in index[i:i + 6]) + "\n")
    out.append("];\n\n")
    out.append("pub const DECOMP_DATA: &[u32] = &[\n")
    for i in range(0, len(flat), 10):
        out.append("    " + " ".join(f"0x{c:X}," for c in flat[i:i + 10]) + "\n")
    out.append("];\n\n")
    out.append("/// The primary composites: (first, second, composite), sorted (canonical composition).\n")
    out.append("pub const COMPOSE: &[(u32, u32, u32)] = &[\n")
    pairs = data["compose"]
    for i in range(0, len(pairs), 5):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, 0x{c:X})," for a, b, c in pairs[i:i + 5]) + "\n")
    out.append("];\n")


#: What the scanner's premise covers: for every code point Unicode 13.0
#: assigns, these read the same on every supported Python (3.10-3.14). The
#: other bits drift with newer Unicode: identifier characters (15.1: ZWNJ,
#: ZWJ, the katakana middle dots, which core handles itself), numeric values
#: (15.1: some CJK ideographs), the Lowercase property of a few modifier
#: letters (15.0) and Case_Ignorable (14.0: U+1734); the engine uses none of
#: them where it would matter, and a test pins each use.
STABLE = ALNUM | DECIMAL | DIGIT | SPACE | ALPHA | LINEBREAK | CASED | PRINTABLE


def check_unicode_here(path):
    """On a Python other than 3.10: every code point Unicode 13.0 assigns
    must read the same here as in the table (STABLE bits and sre's simple
    lowercase; its uppercase too, unless it is a character Unicode 13.0 does
    not have: Unicode 16 gave U+019B and U+0264 new capitals, which pinned
    text never holds); an unassigned one has nothing in the table."""
    import bisect
    from lazaret.scanner import _unicode13
    text = open(path, encoding="utf-8").read()
    want = unicode_data()
    body = text.split("pub const PROPS")[1].split("];")[0]
    starts = sorted((int(a, 16), int(b, 16)) for a, b in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+)\),", body))
    firsts = [s for s, _ in starts]

    def table_flags(c):
        return starts[bisect.bisect_right(firsts, c) - 1][1]

    def table_pairs(name):
        body = text.split(f"pub const {name}:")[1].split("];")[0]
        return {int(a, 16): int(b, 16) for a, b in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+)\)", body)}

    lower, upper = table_pairs("LOWER"), table_pairs("UPPER")
    bad = []
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            if table_flags(c) or c in lower or c in upper:
                bad.append(f"U+{c:04X} is unassigned in Unicode 13.0 but has properties in the table")
        elif (want["flags"][c] ^ table_flags(c)) & STABLE:
            bad.append(f"U+{c:04X} properties {want['flags'][c]:#x} here, {table_flags(c):#x} in the table")
        elif want["lower"].get(c, c) != lower.get(c, c):
            bad.append(f"U+{c:04X} lowercase differs")
        elif want["upper"].get(c, c) != upper.get(c, c) and _unicode13.assigned(want["upper"].get(c, c)):
            bad.append(f"U+{c:04X} uppercase differs")
        if len(bad) > 20:
            break
    def table_lists(name):
        body = text.split(f"pub const {name}:")[1].split("];\n")[0]
        return {int(a, 16): tuple(int(x, 16) for x in re.findall(r"0x([0-9A-F]+)", b))
                for a, b in re.findall(r"\(0x([0-9A-F]+), &\[([^\]]*)\]\)", body)}

    if table_lists("CASE_FIXES") != want["fixes"]:
        bad.append("re's extra case equivalences differ")
    # str.casefold() (BR-2): Unicode's case folding stability policy, checked
    fold, full_lower = table_lists("FULL_FOLD"), table_lists("FULL_LOWER")
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            if c in fold:
                bad.append(f"U+{c:04X} is unassigned in Unicode 13.0 but has a case fold in the table")
        elif tuple(map(ord, chr(c).casefold())) != fold.get(c, full_lower.get(c, (lower.get(c, c),))):
            bad.append(f"U+{c:04X} case fold differs")
        if len(bad) > 20:
            break
    return bad + check_normalization_here(text, want)


def check_normalization_here(text, want):
    """Unicode's normalization stability policy, checked: for every code
    point Unicode 13.0 assigns, this Python's decomposition, combining class
    and compositions are the table's (so NFKC of pinned text is the same on
    every supported Python)."""
    from lazaret.scanner import _unicode13

    def section(name):
        return text.split(f"pub const {name}:")[1].split("];")[0]

    ccc = {}
    for a, b, k in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+), (\d+)\)", section("CCC_RUNS")):
        for c in range(int(a, 16), int(b, 16) + 1):
            ccc[c] = int(k)
    data = [int(x, 16) for x in re.findall(r"0x([0-9A-F]+)", section("DECOMP_DATA"))]
    decomp = {int(c, 16): (bool(int(n, 16) & 0x80), data[int(at):int(at) + (int(n, 16) & 0x7F)])
              for c, at, n in re.findall(r"\(0x([0-9A-F]+), (\d+), 0x([0-9A-F]+)\)", section("DECOMP"))}
    compose = sorted(tuple(int(x, 16) for x in t)
                     for t in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+), 0x([0-9A-F]+)\)", section("COMPOSE")))
    bad = []
    here = {c: k for a, b, k in want["ccc_runs"] for c in range(a, b + 1)}
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            if c in ccc or c in decomp:
                bad.append(f"U+{c:04X} is unassigned in Unicode 13.0 but has normalization data in the table")
        elif here.get(c, 0) != ccc.get(c, 0):
            bad.append(f"U+{c:04X} combining class differs")
        elif want["decomp"].get(c) != decomp.get(c) and c in decomp:
            bad.append(f"U+{c:04X} decomposition differs")
        if len(bad) > 20:
            return bad
    kept = [t for t in want["compose"] if _unicode13.assigned(t[2])]
    if kept != compose:
        bad.append("the primary composites differ")
    return bad


# ---------------- the rule pack ----------------
# The pack is the source (see above). Its values are written as they were
# extracted from core: patterns as {"re", "flags"} (and the token matcher's
# alternatives), sets sorted, tuples and lists in order, maps by key. core's
# values are written the same way to compare the ones both hold.

_FLAG_LETTERS = ((re.I, "i"), (re.M, "m"), (re.S, "s"), (re.X, "x"), (re.A, "a"))


def _flags(rx):
    return "".join(letter for bit, letter in _FLAG_LETTERS if rx.flags & bit)


def _value(v):
    """The pack's form of one value of core, or None when it is not data."""
    if isinstance(v, re.Pattern):
        if not isinstance(v.pattern, str):
            return None                               # (bytes patterns are the file walker's, not text rules)
        return {"re": v.pattern, "flags": _flags(v)}
    if isinstance(v, bool) or v is None:
        return {"value": v}
    if isinstance(v, int) and not -(1 << 63) <= v < (1 << 63):
        return None
    if isinstance(v, (int, float, str)):
        return {"value": v}
    if isinstance(v, (set, frozenset)):
        if not all(isinstance(x, str) for x in v):
            return None
        return {"set": sorted(v)}
    if isinstance(v, (tuple, list)):
        items = [_value(x) for x in v]
        if any(i is None for i in items):
            return None
        return {"list": items}
    if isinstance(v, dict):
        items = {k: _value(x) for k, x in v.items()}
        if any(i is None for i in items.values()) or not all(isinstance(k, str) for k in v):
            return None
        return {"map": items}
    return None


def _patterns(entry, out, where):
    """Each pattern of a pack entry: (where, text, flags)."""
    if isinstance(entry, dict):
        if "re" in entry:
            out.append((where, entry["re"], entry.get("flags", "")))
        for k in ("map",):
            for key, v in entry.get(k, {}).items():
                _patterns(v, out, f"{where}[{key!r}]")
        for k in ("list", "set", "items"):
            for n, v in enumerate(entry.get(k, []) if isinstance(entry.get(k), list) else []):
                _patterns(v, out, f"{where}[{n}]")
    elif isinstance(entry, list):
        for n, v in enumerate(entry):
            _patterns(v, out, f"{where}[{n}]")


_MISSING = object()


def render_pack(data):
    return json.dumps(data, indent=1, sort_keys=True, ensure_ascii=True) + "\n"


def check_pack(text):
    """The pack's problems (see above)."""
    problems = []
    data = json.loads(text)
    if text != render_pack(data):
        problems.append(f"{os.path.relpath(PACK_OUT, REPO)} is not in its canonical form: run "
                        "scripts/make_rust_tables.py")
    try:
        from lazaret.registry.repo import ENGINE_VERSION
    except Exception as e:                            # pragma: no cover
        problems.append(f"cannot read the registry's ENGINE_VERSION: {e}")
    else:
        if data.get("rule_set") != ENGINE_VERSION:
            problems.append(f"the pack's rule_set {data.get('rule_set')!r} is not the registry's ENGINE_VERSION "
                            f"{ENGINE_VERSION!r}")
    found = []
    for name, entry in data.get("values", {}).items():
        _patterns(entry, found, name)
    letters = dict((letter, bit) for bit, letter in _FLAG_LETTERS)
    for where, text_, flags in found:
        bits = 0
        for f in flags:
            bits |= letters.get(f, 0)
        try:
            re.compile(text_, bits)
        except re.error as e:
            problems.append(f"pack pattern {where} does not compile: {e}")
    from lazaret.scanner import core
    shared = 0
    for name, entry in sorted(data.get("values", {}).items()):
        v = vars(core).get(name, _MISSING)
        if v is _MISSING or (callable(v) and not isinstance(v, re.Pattern)):
            continue
        mine = _value(v)
        if mine is not None:
            shared += 1
            if mine != entry:
                problems.append(f"core.{name} differs from the pack's {name}: change both")
    if not shared:
        problems.append("no value of core was compared with the pack (the check is broken)")
    # live secret verification's provider table (V-1): the rules of secretverify.validate, which the engine applies too
    from lazaret.scanner import secretverify
    table = data.get("values", {}).get(secretverify.TABLE)
    try:
        secretverify.validate(table.get("value") if isinstance(table, dict) else None)
    except (ValueError, TypeError, AttributeError) as e:
        problems.append(f"the pack's {secretverify.TABLE}: {e}")
    return problems


def main(argv):
    check = "--check" in argv
    is310 = sys.version_info[:2] == (3, 10)
    problems = []
    for key in [k for k in os.environ if k.startswith("LAZARET_") and k != "LAZARET_NATIVE_LIB"]:
        del os.environ[key]                           # (defaults only: core's values must not depend on the caller)
    from lazaret.scanner.core import configure_stdio  # (after the environment is cleared: core reads it)
    configure_stdio()
    with open(PACK_OUT, encoding="utf-8") as f:
        pack = f.read()
    if check:
        problems += check_pack(pack)
    else:
        with open(PACK_OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(render_pack(json.loads(pack)))
    if check:
        problems += check_case_fixes()
    if is310:
        uni = render_unicode(unicode_data())
        if check:
            if not os.path.exists(UNICODE_OUT) or open(UNICODE_OUT, encoding="utf-8").read() != uni:
                problems.append(f"{os.path.relpath(UNICODE_OUT, REPO)} is stale: run python3.10 "
                                "scripts/make_rust_tables.py")
        else:
            with open(UNICODE_OUT, "w", encoding="utf-8", newline="\n") as f:
                f.write(uni)
    elif check or "--unicode" in argv:
        problems += check_unicode_here(UNICODE_OUT)
    for p in problems:
        print(p, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
