#!/usr/bin/env python3
"""Generate the Unicode 13.0 assignment table both engines pin their input to.

    python3.10 scripts/make_unicode_tables.py            # (re)write all three from unicodedata
    python3 scripts/make_unicode_tables.py               # rewrite the JS copies from the Python module
    python3 scripts/make_unicode_tables.py --check       # exit 1 if any copy is out of date

Python's re and unicodedata, and Node's regexes and ICU, classify code
points by the Unicode version they were built with: U+10D4A is a letter on
Python 3.14 and Node 22 and unassigned on 3.10-3.13, so `\\U00010d4a` +
`eval(x)` was S-EVAL-PY on some Pythons only (\\b before eval). For the code
points Unicode 13.0 assigns (Python 3.10's, the oldest supported) every
property the scanner uses is the same on every supported Python and Node
(\\w, \\d, \\s, NFKC; identifier characters but four, handled in core). So
both engines map every code point Unicode 13.0 leaves unassigned to U+FFFD
before scanning a source file.

Writes python/src/lazaret/scanner/_unicode13.py (the source of truth, from
unicodedata when run on a Python whose Unicode is 13.0.0), and from it
js/src/lib/unicode13.js and the dashboard's copy (its script hash updated).
python/tests/scanner/test_review_unicode_pin.py fails when a copy is stale.
"""
import importlib.util
import os
import sys
import unicodedata

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY_OUT = os.path.join(REPO, "python", "src", "lazaret", "scanner", "_unicode13.py")
JS_OUT = os.path.join(REPO, "js", "src", "lib", "unicode13.js")
DASHBOARD = os.path.join(REPO, "python", "src", "lazaret", "web", "lazaret.html")
SECTION = "/* ======== lib/unicode13.js ======== */"
BEFORE = "/* ======== lib/codecs.js ======== */"      # where the section goes in the page
DIGITS = "0123456789abcdefghijklmnopqrstuvwxyz"

PY_TEMPLATE = '''"""Unicode 13.0's code point assignments (Python 3.10's Unicode, the oldest
supported). Generated by scripts/make_unicode_tables.py — do not edit.

Both engines map every code point Unicode 13.0 leaves unassigned to U+FFFD
before scanning a source file (pin), so a later addition (U+10D4A is a letter
on Python 3.14 and Node 22, unassigned on 3.10-3.13) reads the same on every
Python and Node version: for the code points Unicode 13.0 assigns, \\\\w, \\\\d,
\\\\s and NFKC are the same on all of them.

Data of the Unicode Character Database 13.0 (read from Python 3.10's
unicodedata), distributed under the Unicode License v3 (LICENSE-UNICODE):
    Copyright © 1991-2026 Unicode, Inc.
"""
import bisect

#: Base-36 lengths of alternating runs from U+0000: assigned, unassigned, ...
RUNS = "{runs}"


def _unassigned():
    out, cp, assigned = [], 0, True
    for tok in RUNS.split():
        n = int(tok, 36)
        if not assigned:
            out.append((cp, cp + n - 1))
        cp += n
        assigned = not assigned
    return tuple(out)


#: (first, last) of every unassigned range, in order.
UNASSIGNED = _unassigned()
_FIRSTS = [a for a, _ in UNASSIGNED]


def assigned(cp):
    """Does Unicode 13.0 assign code point `cp` (surrogates and private use
    included)?"""
    k = bisect.bisect_right(_FIRSTS, cp) - 1
    return k < 0 or cp > UNASSIGNED[k][1]


def pin(text):
    """`text` with every code point Unicode 13.0 leaves unassigned replaced by
    U+FFFD (one code point for one: offsets do not move)."""
    if text.isascii():
        return text
    table = {{o: "\\ufffd" for o in map(ord, set(text)) if o >= 0x378 and not assigned(o)}}
    return text.translate(table) if table else text
'''

JS_TEMPLATE = '''// Unicode 13.0's code point assignments — generated by
// scripts/make_unicode_tables.py from lazaret.scanner._unicode13; do not edit.
// Both engines map every code point Unicode 13.0 leaves unassigned to U+FFFD
// before scanning a source file (pinUnicode), so a later addition reads the
// same on every Python and Node version (see the Python module).
// Data of the Unicode Character Database 13.0, distributed under the Unicode
// License v3 (LICENSE-UNICODE): Copyright © 1991-2026 Unicode, Inc.

// Base-36 lengths of alternating runs from U+0000: assigned, unassigned, ...
const UNICODE13_RUNS = "{runs}";
const UNASSIGNED13 = [];                                 // [first, last] ranges, in order
{{
  let cp = 0, assigned = true;
  for (const tok of UNICODE13_RUNS.split(" ")) {{
    const n = parseInt(tok, 36);
    if (!assigned) UNASSIGNED13.push([cp, cp + n - 1]);
    cp += n;
    assigned = !assigned;
  }}
}}
const cpEscape = (c) => `\\\\u{{${{c.toString(16)}}}}`;
const UNASSIGNED13_RE = new RegExp("[" + UNASSIGNED13.map(([a, b]) => (a === b ? cpEscape(a) : cpEscape(a) + "-" + cpEscape(b))).join("") + "]", "gu");

/** Does Unicode 13.0 assign code point cp (surrogates and private use included)? */
export function assigned13(cp) {{
  let lo = 0, hi = UNASSIGNED13.length;
  while (lo < hi) {{ const mid = (lo + hi) >> 1; if (UNASSIGNED13[mid][0] <= cp) lo = mid + 1; else hi = mid; }}
  return lo === 0 || cp > UNASSIGNED13[lo - 1][1];
}}

/** text with every code point Unicode 13.0 leaves unassigned as U+FFFD (core._unicode13.pin). */
export function pinUnicode(text) {{
  return /[^\\x00-\\x7f]/.test(text) ? text.replace(UNASSIGNED13_RE, "\\ufffd") : text;
}}
'''


def _configure_stdio():
    """Same policy as lazaret.scanner.core.configure_stdio (STRUCTURE.md,
    "Cross-platform rules")."""
    explicit = bool(os.environ.get("PYTHONIOENCODING"))
    for stream in (sys.stdout, sys.stderr):
        try:
            encoding = (getattr(stream, "encoding", None) or "").lower().replace("_", "-")
            if not explicit and not stream.isatty() and encoding not in ("utf-8", "utf8"):
                stream.reconfigure(encoding="utf-8", errors="replace")
            else:
                stream.reconfigure(errors="replace")
        except (AttributeError, OSError, ValueError):
            pass


def b36(n):
    out = ""
    while True:
        n, r = divmod(n, 36)
        out = DIGITS[r] + out
        if not n:
            return out


def runs_from_unicodedata():
    """RUNS computed from this interpreter's unicodedata (13.0.0 wanted)."""
    runs, cp, start, assigned = [], 0, 0, True
    for cp in range(0x110000):
        a = (0xD800 <= cp <= 0xDFFF) or unicodedata.category(chr(cp)) != "Cn"
        if a != assigned:
            runs.append(cp - start)
            start, assigned = cp, a
    runs.append(0x110000 - start)
    return " ".join(b36(n) for n in runs)


def committed_runs():
    spec = importlib.util.spec_from_file_location("_unicode13_committed", PY_OUT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.RUNS


def dashboard_text(html, module):
    body = "\n".join(line[len("export "):] if line.startswith("export ") else line for line in module.split("\n"))
    block = SECTION + "\n" + body + "\n"
    if SECTION in html:
        start = html.index(SECTION)
        end = html.index("/* ======== ", start + len(SECTION))
        return html[:start] + block + html[end:]
    at = html.index(BEFORE)
    return html[:at] + block + html[at:]


def _dashboard_csp():
    spec = importlib.util.spec_from_file_location("_dashboard_csp", os.path.join(REPO, "scripts", "dashboard_csp.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def _read(path):
    try:
        with open(path, encoding="utf-8", newline="") as f:
            return f.read().replace("\r\n", "\n")
    except FileNotFoundError:
        return None


def main(argv=None):
    _configure_stdio()
    args = sys.argv[1:] if argv is None else list(argv)
    check = "--check" in args
    if unicodedata.unidata_version == "13.0.0":
        runs = runs_from_unicodedata()
    else:
        runs = committed_runs()
    want = {PY_OUT: PY_TEMPLATE.format(runs=runs), JS_OUT: JS_TEMPLATE.format(runs=runs)}
    html = _read(DASHBOARD)
    want[DASHBOARD] = dashboard_text(html, want[JS_OUT])
    stale = [p for p, text in want.items() if _read(p) != text]
    if check:
        for path in stale:
            print(f"{path}: out of date; run python3 scripts/make_unicode_tables.py", file=sys.stderr)
        return 1 if stale else 0
    for path in stale:
        text = _dashboard_csp().with_hashes(want[path]) if path == DASHBOARD else want[path]
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"{path}: written")
    if not stale:
        print("Unicode tables up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
