#!/usr/bin/env python3
"""Generate the Rust engine's data from the Python reference engine.

    python3.10 scripts/make_rust_tables.py          # (re)write both files
    python3 scripts/make_rust_tables.py             # rewrite the rule pack only
    python3 scripts/make_rust_tables.py --check     # exit 1 if either is stale

Nothing in either file is ever edited by hand (docs/RUST_ENGINE.md, "Single
source of truth for patterns"):

* rust/crates/lazaret-engine/rules/lazaret-rules.json, the rule pack: every
  pattern of lazaret.scanner.core (its text and flags), every (exact,
  candidate) pattern pair, the pattern text core composes further, the name
  sets, tables and limits, keyed by core's own names (received_spec.json's
  too, through core). The Rust engine embeds it and reads it at run time,
  compiling each pattern's text with its own implementation of Python's `re`
  (crates/lazaret-engine/src/pyre): the text Python compiles, byte for byte.
  The Python package can also hand the engine core's live values, so a stale
  copy can never be what runs. Written from any supported Python.

* rust/crates/lazaret-engine/src/generated/unicode13.rs: the character data
  the engine reads source text with, from Unicode 13.0 (Python 3.10's
  unicodedata, the oldest supported, which the scanner pins source text to:
  lazaret/scanner/_unicode13.py). What Python's `re` and `str` use: \\w
  (isalnum), \\d (isdecimal), \\s (isspace), the simple case mappings sre
  folds with, the full case mappings and the Final_Sigma context of
  str.lower(), re's extra case equivalences (ſ → s, K → k, …), printable and
  identifier characters. Only Python 3.10 writes it; on any other Python,
  --check verifies that every code point Unicode 13.0 assigns reads the same
  there for the properties the scanner relies on (STABLE), and that the table
  holds nothing for the ones Unicode 13.0 leaves unassigned.
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GEN = os.path.join(REPO, "rust", "crates", "lazaret-engine", "src", "generated")
UNICODE_OUT = os.path.join(GEN, "unicode13.rs")
PACK_OUT = os.path.join(REPO, "rust", "crates", "lazaret-engine", "rules", "lazaret-rules.json")
sys.path.insert(0, os.path.join(REPO, "python", "src"))

MAX_CP = 0x110000
HEADER = "// Generated by scripts/make_rust_tables.py from {src} — do not edit.\n"

# ---- property bits (crates/lazaret-engine/src/unicode.rs names them) ----
ALNUM, DECIMAL, DIGIT, SPACE, ALPHA, LINEBREAK, CASED, CASE_IGNORABLE = (1 << i for i in range(8))
PRINTABLE, NUMERIC, ID_START, ID_CONTINUE, UPPER, LOWER, TITLE = (1 << i for i in range(8, 15))


def _linebreaks():
    """Py_UNICODE_ISLINEBREAK: the characters str.splitlines() splits at."""
    return frozenset(c for c in range(MAX_CP) if len(("a" + chr(c) + "b").splitlines()) == 2)


def props(c, linebreaks):
    """The property bits of code point c on this Python."""
    ch = chr(c)
    f = 0
    if ch.isalnum():
        f |= ALNUM
    if ch.isdecimal():
        f |= DECIMAL
    if ch.isdigit():
        f |= DIGIT
    if ch.isspace():
        f |= SPACE
    if ch.isalpha():
        f |= ALPHA
    if c in linebreaks:
        f |= LINEBREAK
    # str.lower()'s Final_Sigma context reads Cased and Case_Ignorable, which
    # Python does not expose; they are read back from lower() itself. A
    # case-ignorable character is skipped whatever else it is, so CASED is
    # the property of a character that is not case-ignorable:
    #   ("A" + ch + "Σ") is final  <=>  ch is case-ignorable or cased
    #   (ch + "Σ") is final        <=>  ch is not case-ignorable and cased
    t1 = ("A" + ch + "Σ").lower()[-1] == "ς"
    t2 = (ch + "Σ").lower()[-1] == "ς"
    if t2:
        f |= CASED
    if t1 and not t2:
        f |= CASE_IGNORABLE
    if ch.isprintable():
        f |= PRINTABLE
    if ch.isnumeric():
        f |= NUMERIC
    if ch.isidentifier():
        f |= ID_START
    if ("a" + ch).isidentifier():
        f |= ID_CONTINUE
    if ch.isupper():
        f |= UPPER
    if ch.islower():
        f |= LOWER
    if ch.istitle():
        f |= TITLE
    return f


def sre_lower(c):
    import _sre
    return _sre.unicode_tolower(c)


def sre_upper(c):
    """_PyUnicode_ToUppercase: the simple mapping, or the first character of
    the full one for a character SpecialCasing lists (what sre's
    RANGE_UNI_IGNORE reads)."""
    u = chr(c).upper()
    return ord(u[0]) if u else c


def case_fixes():
    try:
        from re._casefix import _EXTRA_CASES as fixes            # 3.11+
    except ImportError:
        import sre_compile                                        # 3.10
        fixes = sre_compile._ignorecase_fixes
    return {k: tuple(v) for k, v in fixes.items()}


def unicode_data():
    """Everything unicode13.rs holds, from this Python."""
    lb = _linebreaks()
    flags = [props(c, lb) for c in range(MAX_CP)]
    lower = {c: sre_lower(c) for c in range(MAX_CP) if sre_lower(c) != c}
    upper = {c: sre_upper(c) for c in range(MAX_CP) if sre_upper(c) != c}
    full_lower = {}
    for c in range(MAX_CP):
        if c == 0x3A3:
            continue                              # Σ: its context decides (unicode.rs)
        low = chr(c).lower()
        if len(low) != 1 or ord(low) != lower.get(c, c):
            full_lower[c] = [ord(x) for x in low]
    full_upper = {}
    for c in range(MAX_CP):
        up = chr(c).upper()
        if len(up) != 1 or ord(up) != upper.get(c, c):
            full_upper[c] = [ord(x) for x in up]
    import unicodedata
    decimal_runs = []                              # (first, last, value of first): int() of a digit
    for ch in range(MAX_CP):
        if flags[ch] & DECIMAL:
            v = unicodedata.decimal(chr(ch))
            if decimal_runs and decimal_runs[-1][1] == ch - 1 and \
                    decimal_runs[-1][2] + (ch - decimal_runs[-1][0]) == v:
                decimal_runs[-1][1] = ch
            else:
                decimal_runs.append([ch, ch, v])
    return {"flags": flags, "lower": lower, "upper": upper, "full_lower": full_lower,
            "full_upper": full_upper, "fixes": case_fixes(), "decimal_runs": decimal_runs,
            **normalization_data()}


HANGUL_FIRST, HANGUL_LAST = 0xAC00, 0xD7A3         # syllables: decomposed and composed by arithmetic
#                                                 # (3.13's unicodedata.decomposition lists them, 3.10's not)


def normalization_data():
    """What unicodedata.normalize reads, from this Python: each code point's
    decomposition, one level (unicodedata.decomposition: canonical, or a
    compatibility mapping; Hangul syllables are computed, not listed), the
    canonical combining classes, and the primary composites (a canonical
    decomposition into two characters, the first a starter, that is not
    excluded from composition: NFC gives the character back)."""
    import unicodedata
    decomp, ccc_runs = {}, []                      # cp -> (compatibility?, [cp, …]); [first, last, class]
    for c in range(MAX_CP):
        ch = chr(c)
        d = unicodedata.decomposition(ch) if not HANGUL_FIRST <= c <= HANGUL_LAST else ""
        if d:
            parts = d.split()
            compat = parts[0].startswith("<")
            decomp[c] = (compat, [int(x, 16) for x in (parts[1:] if compat else parts)])
        k = unicodedata.combining(ch)
        if k:
            if ccc_runs and ccc_runs[-1][1] == c - 1 and ccc_runs[-1][2] == k:
                ccc_runs[-1][1] = c
            else:
                ccc_runs.append([c, c, k])
    compose = sorted((parts[0], parts[1], c) for c, (compat, parts) in decomp.items()
                     if not compat and len(parts) == 2 and not unicodedata.combining(chr(parts[0]))
                     and unicodedata.normalize("NFC", chr(c)) == chr(c))
    return {"decomp": decomp, "ccc_runs": ccc_runs, "compose": compose}


def render_unicode(data):
    from lazaret.scanner import _unicode13
    runs = []
    prev = None
    for c, f in enumerate(data["flags"]):
        if f != prev:
            runs.append((c, f))
            prev = f
    out = [HEADER.format(src="Python 3.10's unicodedata (Unicode 13.0.0)"),
           "#![allow(clippy::unreadable_literal)]\n\n",
           "/// Lengths of alternating runs from U+0000: assigned, unassigned, … (_unicode13.RUNS).\n",
           "pub const ASSIGNED_RUNS: &[u32] = &[",
           ", ".join(str(int(t, 36)) for t in _unicode13.RUNS.split()), "];\n\n",
           "/// (first code point, property bits) of each run of equal properties.\n",
           f"pub const PROPS: &[(u32, u16)] = &[\n"]
    for i in range(0, len(runs), 8):
        out.append("    " + " ".join(f"(0x{c:X}, 0x{f:X})," for c, f in runs[i:i + 8]) + "\n")
    out.append("];\n\n")

    def pairs(name, doc, table):
        out.append(f"/// {doc}\n")
        out.append(f"pub const {name}: &[(u32, u32)] = &[\n")
        items = sorted(table.items())
        for i in range(0, len(items), 8):
            out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X})," for a, b in items[i:i + 8]) + "\n")
        out.append("];\n\n")

    def lists(name, doc, table):
        out.append(f"/// {doc}\n")
        out.append(f"pub const {name}: &[(u32, &[u32])] = &[\n")
        for a, bs in sorted(table.items()):
            out.append(f"    (0x{a:X}, &[" + ", ".join(f"0x{b:X}" for b in bs) + "]),\n")
        out.append("];\n\n")

    pairs("LOWER", "sre's simple lowercase (_sre.unicode_tolower) where it is not the character itself.",
          data["lower"])
    pairs("UPPER", "sre's uppercase (_PyUnicode_ToUppercase) where it is not the character itself.",
          data["upper"])
    lists("FULL_LOWER", "str.lower() where it is not LOWER's one character (Σ excepted: its context decides).",
          data["full_lower"])
    lists("FULL_UPPER", "str.upper() where it is not UPPER's one character.", data["full_upper"])
    lists("CASE_FIXES", "re's extra case equivalences (re._casefix._EXTRA_CASES): lowercase -> the others.",
          data["fixes"])
    out.append("/// (first, last, value of first) of each run of decimal digits: int() reads them.\n")
    out.append("pub const DECIMAL_RUNS: &[(u32, u32, u32)] = &[\n")
    runs = data["decimal_runs"]
    for i in range(0, len(runs), 6):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, {v})," for a, b, v in runs[i:i + 6]) + "\n")
    out.append("];\n\n")
    render_normalization(out, data)
    return "".join(out)


def render_normalization(out, data):
    out.append("/// (first, last, class) of each run of code points with the same canonical combining class\n"
               "/// (unicodedata.combining), those with a class other than 0.\n")
    out.append("pub const CCC_RUNS: &[(u32, u32, u8)] = &[\n")
    runs = data["ccc_runs"]
    for i in range(0, len(runs), 6):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, {k})," for a, b, k in runs[i:i + 6]) + "\n")
    out.append("];\n\n")
    flat, index = [], []
    for c, (compat, parts) in sorted(data["decomp"].items()):
        index.append((c, len(flat), len(parts) | (0x80 if compat else 0)))
        flat.extend(parts)
    out.append("/// Each decomposition, one level (unicodedata.decomposition; Hangul syllables are computed):\n"
               "/// (code point, start in DECOMP_DATA, length, + 0x80 for a compatibility mapping).\n")
    out.append("pub const DECOMP: &[(u32, u16, u8)] = &[\n")
    for i in range(0, len(index), 6):
        out.append("    " + " ".join(f"(0x{c:X}, {at}, 0x{n:X})," for c, at, n in index[i:i + 6]) + "\n")
    out.append("];\n\n")
    out.append("pub const DECOMP_DATA: &[u32] = &[\n")
    for i in range(0, len(flat), 10):
        out.append("    " + " ".join(f"0x{c:X}," for c in flat[i:i + 10]) + "\n")
    out.append("];\n\n")
    out.append("/// The primary composites: (first, second, composite), sorted (canonical composition).\n")
    out.append("pub const COMPOSE: &[(u32, u32, u32)] = &[\n")
    pairs = data["compose"]
    for i in range(0, len(pairs), 5):
        out.append("    " + " ".join(f"(0x{a:X}, 0x{b:X}, 0x{c:X})," for a, b, c in pairs[i:i + 5]) + "\n")
    out.append("];\n")


#: What the scanner's premise covers: for every code point Unicode 13.0
#: assigns, these read the same on every supported Python (3.10-3.14). The
#: other bits drift with newer Unicode: identifier characters (15.1: ZWNJ,
#: ZWJ, the katakana middle dots, which core handles itself), numeric values
#: (15.1: some CJK ideographs), the Lowercase property of a few modifier
#: letters (15.0) and Case_Ignorable (14.0: U+1734); the engine uses none of
#: them where it would matter, and a test pins each use.
STABLE = ALNUM | DECIMAL | DIGIT | SPACE | ALPHA | LINEBREAK | CASED | PRINTABLE


def check_unicode_here(path):
    """On a Python other than 3.10: every code point Unicode 13.0 assigns
    must read the same here as in the table (STABLE bits and sre's simple
    lowercase; its uppercase too, unless it is a character Unicode 13.0 does
    not have: Unicode 16 gave U+019B and U+0264 new capitals, which pinned
    text never holds); an unassigned one has nothing in the table."""
    import bisect
    from lazaret.scanner import _unicode13
    text = open(path, encoding="utf-8").read()
    want = unicode_data()
    body = text.split("pub const PROPS")[1].split("];")[0]
    starts = sorted((int(a, 16), int(b, 16)) for a, b in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+)\),", body))
    firsts = [s for s, _ in starts]

    def table_flags(c):
        return starts[bisect.bisect_right(firsts, c) - 1][1]

    def table_pairs(name):
        body = text.split(f"pub const {name}:")[1].split("];")[0]
        return {int(a, 16): int(b, 16) for a, b in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+)\)", body)}

    lower, upper = table_pairs("LOWER"), table_pairs("UPPER")
    bad = []
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            if table_flags(c) or c in lower or c in upper:
                bad.append(f"U+{c:04X} is unassigned in Unicode 13.0 but has properties in the table")
        elif (want["flags"][c] ^ table_flags(c)) & STABLE:
            bad.append(f"U+{c:04X} properties {want['flags'][c]:#x} here, {table_flags(c):#x} in the table")
        elif want["lower"].get(c, c) != lower.get(c, c):
            bad.append(f"U+{c:04X} lowercase differs")
        elif want["upper"].get(c, c) != upper.get(c, c) and _unicode13.assigned(want["upper"].get(c, c)):
            bad.append(f"U+{c:04X} uppercase differs")
        if len(bad) > 20:
            break
    body = text.split("pub const CASE_FIXES:")[1].split("];\n")[0]
    table = {int(a, 16): tuple(int(x, 16) for x in re.findall(r"0x([0-9A-F]+)", b))
             for a, b in re.findall(r"\(0x([0-9A-F]+), &\[([^\]]*)\]\)", body)}
    if table != want["fixes"]:
        bad.append("re's extra case equivalences differ")
    return bad + check_normalization_here(text, want)


def check_normalization_here(text, want):
    """Unicode's normalization stability policy, checked: for every code
    point Unicode 13.0 assigns, this Python's decomposition, combining class
    and compositions are the table's (so NFKC of pinned text is the same on
    every supported Python)."""
    from lazaret.scanner import _unicode13

    def section(name):
        return text.split(f"pub const {name}:")[1].split("];")[0]

    ccc = {}
    for a, b, k in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+), (\d+)\)", section("CCC_RUNS")):
        for c in range(int(a, 16), int(b, 16) + 1):
            ccc[c] = int(k)
    data = [int(x, 16) for x in re.findall(r"0x([0-9A-F]+)", section("DECOMP_DATA"))]
    decomp = {int(c, 16): (bool(int(n, 16) & 0x80), data[int(at):int(at) + (int(n, 16) & 0x7F)])
              for c, at, n in re.findall(r"\(0x([0-9A-F]+), (\d+), 0x([0-9A-F]+)\)", section("DECOMP"))}
    compose = sorted(tuple(int(x, 16) for x in t)
                     for t in re.findall(r"\(0x([0-9A-F]+), 0x([0-9A-F]+), 0x([0-9A-F]+)\)", section("COMPOSE")))
    bad = []
    here = {c: k for a, b, k in want["ccc_runs"] for c in range(a, b + 1)}
    for c in range(MAX_CP):
        if not _unicode13.assigned(c):
            if c in ccc or c in decomp:
                bad.append(f"U+{c:04X} is unassigned in Unicode 13.0 but has normalization data in the table")
        elif here.get(c, 0) != ccc.get(c, 0):
            bad.append(f"U+{c:04X} combining class differs")
        elif want["decomp"].get(c) != decomp.get(c) and c in decomp:
            bad.append(f"U+{c:04X} decomposition differs")
        if len(bad) > 20:
            return bad
    kept = [t for t in want["compose"] if _unicode13.assigned(t[2])]
    if kept != compose:
        bad.append("the primary composites differ")
    return bad


# ---------------- the rule pack ----------------
# Every module-level value of lazaret.scanner.core that is data: compiled
# patterns (their text and flags), (exact, candidate) pattern pairs, pattern
# text core composes further, name sets, tables and limits. Keyed by core's
# own names, so the Rust engine (and later core itself, when the pack becomes
# the source: docs/RUST_ENGINE.md) reads exactly what core holds. Sets are
# written sorted (their iteration order is not Python's to keep), tuples and
# lists in order.

_FLAG_LETTERS = ((re.I, "i"), (re.M, "m"), (re.S, "s"), (re.X, "x"), (re.A, "a"))


def _flags(rx):
    return "".join(letter for bit, letter in _FLAG_LETTERS if rx.flags & bit)


def _value(v):
    """The JSON form of one value of core, or None when it is not data."""
    if isinstance(v, re.Pattern):
        if not isinstance(v.pattern, str):
            return None                               # (bytes patterns are the file walker's, not text rules)
        return {"re": v.pattern, "flags": _flags(v)}
    if isinstance(v, _token_pattern_type()):
        # core's linear-time matcher of "|".join(alternatives), the last one
        # the JWT alternative (S-TOKEN, secret redaction): its text, and the
        # alternatives the engine matches the same way
        return {"re": v.pattern, "flags": _flags(v), "token": list(v.alternatives)}
    if isinstance(v, bool) or v is None:
        return {"value": v}
    if isinstance(v, int) and not -(1 << 63) <= v < (1 << 63):
        return None                                   # (_INT_STR_LIMIT: Python's own int-to-str limit)
    if isinstance(v, (int, float, str)):
        return {"value": v}
    if isinstance(v, (set, frozenset)):
        items = [_value(x) for x in v]
        if any(i is None for i in items) or not all(isinstance(x, str) for x in v):
            return None
        return {"set": sorted(v)}
    if isinstance(v, (tuple, list)):
        items = [_value(x) for x in v]
        if any(i is None for i in items):
            return None
        return {"list": items}
    if isinstance(v, dict):
        items = {k: _value(x) for k, x in v.items()}
        if any(i is None for i in items.values()):
            return None
        if all(isinstance(k, str) for k in v):
            return {"map": items}
        # other keys (None, tuples of str: the lexer's tables): [key, value] pairs
        keys = [_key(k) for k in v]
        if any(k is _NOT_DATA for k in keys):
            return None
        return {"items": [[k, items[orig]] for k, orig in sorted(zip(keys, v), key=lambda kv: json.dumps(kv[0]))]}
    return None


_NOT_DATA = object()


def _token_pattern_type():
    from lazaret.scanner import core
    return core._TokenPattern


def _key(k):
    if k is None or isinstance(k, str):
        return k
    if isinstance(k, tuple) and all(isinstance(x, str) or x is None for x in k):
        return list(k)
    return _NOT_DATA


# Values of core that come from the operating system, not from the rules: the
# pack must be the same on every platform (CI runs --check on Linux, macOS and
# Windows), and the engine does no I/O. tests/architecture/test_rust_pack.py
# imports core with the OS's constants changed and fails on any other value
# that moves with them.
PLATFORM_VALUES = frozenset({
    "_OPEN_FLAGS",          # os.open flags: O_NOFOLLOW, O_NONBLOCK, O_CLOEXEC, O_BINARY … differ by OS
})
# Values that change with every release, not with the rules: a version bump
# must not make the pack stale (0.1.8's bump failed --check on VERSION). The
# engine reports its own version (the workspace's, held to the packages' by
# scripts/check-versions.sh).
RELEASE_VALUES = frozenset({
    "VERSION",              # lazaret.__version__, what --version prints
})


def pack_data():
    from lazaret.scanner import core
    try:
        from lazaret.registry.repo import ENGINE_VERSION
    except Exception:                                  # pragma: no cover (the registry imports the scanner)
        ENGINE_VERSION = None
    values = {}
    for name in sorted(vars(core)):
        if name.startswith("__") or name in PLATFORM_VALUES or name in RELEASE_VALUES:
            continue
        v = getattr(core, name)
        if callable(v) and not isinstance(v, re.Pattern):
            continue
        j = _value(v)
        if j is not None:
            values[name] = j
    return {"format": 1, "rule_set": ENGINE_VERSION,
            "source": "lazaret.scanner.core, extracted by scripts/make_rust_tables.py — do not edit",
            "values": values}


def render_pack(data):
    return json.dumps(data, indent=1, sort_keys=True, ensure_ascii=True) + "\n"


def main(argv):
    check = "--check" in argv
    is310 = sys.version_info[:2] == (3, 10)
    problems = []
    for key in [k for k in os.environ if k.startswith("LAZARET_")]:
        del os.environ[key]                           # (defaults only: the pack must not depend on the caller)
    from lazaret.scanner.core import configure_stdio  # (after the environment is cleared: core reads it)
    configure_stdio()
    pack = render_pack(pack_data())
    if check:
        if not os.path.exists(PACK_OUT) or open(PACK_OUT, encoding="utf-8").read() != pack:
            problems.append(f"{os.path.relpath(PACK_OUT, REPO)} is stale: run scripts/make_rust_tables.py")
    else:
        os.makedirs(os.path.dirname(PACK_OUT), exist_ok=True)
        with open(PACK_OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(pack)
    if is310:
        uni = render_unicode(unicode_data())
        if check:
            if not os.path.exists(UNICODE_OUT) or open(UNICODE_OUT, encoding="utf-8").read() != uni:
                problems.append(f"{os.path.relpath(UNICODE_OUT, REPO)} is stale: run python3.10 "
                                "scripts/make_rust_tables.py")
        else:
            with open(UNICODE_OUT, "w", encoding="utf-8", newline="\n") as f:
                f.write(uni)
    elif check or "--unicode" in argv:
        problems += check_unicode_here(UNICODE_OUT)
    for p in problems:
        print(p, file=sys.stderr)
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
