#!/usr/bin/env python3
"""Generate js/src/lib/codecs.js: the Python codecs a PEP 263 coding cookie
can name, for the npm engine and the dashboard (which carries a copy).

    python3 scripts/make_codec_tables.py            # rewrite codecs.js and the dashboard's copy
    python3 scripts/make_codec_tables.py --check    # exit 1 if either is out of date

Both engines must decode a Python file with a coding cookie to the same
text. The npm engine has no Python codecs and the browser's TextDecoder
knows only some of them, and not always with Python's tables (cp1252's
undefined bytes, cp866, ISO-8859-16, …). This writes, from Python's own
codecs as lazaret.scanner.core resolves them:

  PY_CODEC_ALIASES    every codec -> the (normalized) names that resolve to it:
                      encodings.aliases, the encodings package, and
                      core.CODEC_ALIAS_EXTRAS (names only newer Pythons know);
                      not core.HOST_CODECS (the host's code page);
  SINGLE_BYTE_CODECS  every single-byte (charmap) codec -> what bytes
                      0x80..0xFF decode to (all 256 bytes when 0x00..0x7F are
                      not ASCII), U+FFFD for a byte the codec leaves undefined
                      (what errors="replace" gives), core.CHARMAP_FIXES applied.

The output is the same on every supported Python (3.10-3.14), and
python/tests/scanner/test_review_codecs.py fails when it is not current.
Run scripts/dashboard_csp.py is not needed afterwards: the dashboard's
script hash is updated here.
"""
import codecs
import importlib.util
import json
import os
import pkgutil
import sys
import unicodedata

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "js", "src", "lib", "codecs.js")
DASHBOARD = os.path.join(REPO, "python", "src", "lazaret", "web", "lazaret.html")
SECTION = "/* ======== lib/codecs.js ======== */"

HEADER = """\
// Generated by scripts/make_codec_tables.py from Python's codecs, as
// lazaret.scanner.core resolves them — do not edit; rerun the script.
//
// PY_CODEC_ALIASES: codec name (codecs.lookup(name).name) -> every name that
// resolves to it, normalized like encodings.normalize_encoding (lower case,
// non-alphanumerics except '.' -> '_'), on every supported Python.
// SINGLE_BYTE_CODECS: single-byte codec -> the characters bytes 0x80..0xFF
// decode to (all 256 bytes when 0x00..0x7F are not ASCII); U+FFFD where the
// codec leaves a byte undefined (Python's errors="replace").
"""


def _configure_stdio():
    """Same policy as lazaret.scanner.core.configure_stdio (STRUCTURE.md,
    "Cross-platform rules")."""
    explicit = bool(os.environ.get("PYTHONIOENCODING"))
    for stream in (sys.stdout, sys.stderr):
        try:
            encoding = (getattr(stream, "encoding", None) or "").lower().replace("_", "-")
            if not explicit and not stream.isatty() and encoding not in ("utf-8", "utf8"):
                stream.reconfigure(encoding="utf-8", errors="replace")
            else:
                stream.reconfigure(errors="replace")
        except (AttributeError, OSError, ValueError):
            pass


def _core():
    src = os.path.join(REPO, "python", "src")
    if src not in sys.path:
        sys.path.insert(0, src)
    from lazaret.scanner import core
    return core


def codec_aliases(core):
    import encodings
    import encodings.aliases
    names = set(encodings.aliases.aliases) | set(encodings.aliases.aliases.values())
    names |= {m.name for m in pkgutil.iter_modules(encodings.__path__)}
    names |= set(core.CODEC_ALIAS_EXTRAS)
    table = {}
    for name in sorted(names):
        codec = core.CODEC_ALIAS_EXTRAS.get(name)
        if codec is None:
            try:
                info = codecs.lookup(name)
            except LookupError:
                continue
            if not getattr(info, "_is_text_encoding", True) or info.name in core.HOST_CODECS:
                continue
            codec = info.name
        table.setdefault(codec, []).append(name)
    return {codec: sorted(v) for codec, v in sorted(table.items())}


def _safe(ch):
    """Written as itself in the generated source (else escaped)."""
    o = ord(ch)
    if 0x20 <= o < 0x7F:
        return ch not in '"\\'
    return o > 0xA0 and o not in (0xAD, 0xFFFD) and unicodedata.category(ch) not in (
        "Mn", "Me", "Mc", "Cc", "Cf", "Co", "Cn", "Cs", "Zs", "Zl", "Zp")


def js_string(s):
    out = []
    for ch in s:
        o = ord(ch)
        if _safe(ch):
            out.append(ch)
        elif ch in '"\\':
            out.append("\\" + ch)
        elif o < 0x100:
            out.append(f"\\x{o:02x}")
        else:
            out.append(f"\\u{o:04x}")
    return '"' + "".join(out) + '"'


def single_byte_tables(core, codec_names):
    out = {}
    for codec in codec_names:
        table = core.charmap_table(codec)
        if table is None:
            continue
        table = table.replace("￾", "�")
        assert all(ord(c) < 0x10000 for c in table), codec
        out[codec] = table[128:] if all(ord(table[i]) == i for i in range(128)) else table
    return out


def module_text(core):
    aliases = codec_aliases(core)
    tables = single_byte_tables(core, aliases)
    lines = [HEADER, "export const PY_CODEC_ALIASES = {"]
    lines += [f"  {json.dumps(codec)}: [{', '.join(json.dumps(a) for a in names)}]," for codec, names in aliases.items()]
    lines += ["};", "", "export const SINGLE_BYTE_CODECS = {"]
    lines += [f"  {json.dumps(codec)}: {js_string(table)}," for codec, table in tables.items()]
    lines += ["};", ""]
    return "\n".join(lines)


def dashboard_text(html, module):
    """The dashboard with its lib/codecs.js section replaced by `module`."""
    start = html.index(SECTION)
    end = html.index("/* ======== ", start + len(SECTION))
    body = "\n".join(line[len("export "):] if line.startswith("export const ") else line
                     for line in module.split("\n"))
    return html[:start] + SECTION + "\n" + body + "\n" + html[end:]


def _dashboard_csp():
    spec = importlib.util.spec_from_file_location("_dashboard_csp", os.path.join(REPO, "scripts", "dashboard_csp.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def main(argv=None):
    _configure_stdio()
    args = sys.argv[1:] if argv is None else list(argv)
    check = "--check" in args
    module = module_text(_core())
    with open(DASHBOARD, encoding="utf-8", newline="") as f:
        html = f.read()
    want_html = dashboard_text(html.replace("\r\n", "\n"), module)
    try:
        with open(OUT, encoding="utf-8", newline="") as f:
            current = f.read().replace("\r\n", "\n")
    except FileNotFoundError:
        current = None
    stale = [p for p, ok in ((OUT, current == module),
                             (DASHBOARD, want_html == html.replace("\r\n", "\n"))) if not ok]
    if check:
        for path in stale:
            print(f"{path}: out of date; run python3 scripts/make_codec_tables.py", file=sys.stderr)
        return 1 if stale else 0
    if OUT in stale:
        with open(OUT, "w", encoding="utf-8", newline="\n") as f:
            f.write(module)
    if DASHBOARD in stale:
        with open(DASHBOARD, "w", encoding="utf-8", newline="\n") as f:
            f.write(_dashboard_csp().with_hashes(want_html))
    for path in stale:
        print(f"{path}: written")
    if not stale:
        print("codec tables up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
